/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Flashcard {
  'front' : string,
  'cardType' : string,
  'back' : string,
  'difficulty' : string,
}
export interface FlashcardTopic {
  'id' : string,
  'cards' : Array<Flashcard>,
  'sessionId' : string,
  'topicName' : string,
}
export type Media = Uint8Array;
export interface MindMap {
  'id' : string,
  'mapData' : string,
  'sessionId' : string,
}
export interface Note {
  'id' : string,
  'content' : string,
  'headings' : Array<string>,
  'type' : string,
  'sessionId' : string,
}
export interface Podcast {
  'id' : string,
  'script' : string,
  'mode' : string,
  'sessionId' : string,
}
export interface Quiz {
  'id' : string,
  'questions' : Array<QuizQuestion>,
  'sessionId' : string,
}
export interface QuizQuestion {
  'question' : string,
  'explanation' : string,
  'type' : string,
  'answer' : string,
  'options' : Array<string>,
}
export interface StudySession {
  'id' : string,
  'status' : string,
  'title' : string,
  'subject' : string,
  'createdAt' : bigint,
  'sourceUrl' : string,
  'sourceType' : string,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addMedia' : ActorMethod<[string, Media], undefined>,
  'createFlashcardTopic' : ActorMethod<[FlashcardTopic], undefined>,
  'createMindMap' : ActorMethod<[MindMap], undefined>,
  'createNote' : ActorMethod<[Note], undefined>,
  'createPodcast' : ActorMethod<[Podcast], undefined>,
  'createQuiz' : ActorMethod<[Quiz], undefined>,
  'createSession' : ActorMethod<
    [string, string, string, string, string],
    StudySession
  >,
  'deleteMedia' : ActorMethod<[string], undefined>,
  'deleteSession' : ActorMethod<[string], undefined>,
  'generateSampleContent' : ActorMethod<[string, string], undefined>,
  'getAllSessions' : ActorMethod<
    [[] | [string], [] | [string]],
    Array<StudySession>
  >,
  'getFlashcardTopic' : ActorMethod<[string], FlashcardTopic>,
  'getFlashcardTopicsBySession' : ActorMethod<[string], Array<FlashcardTopic>>,
  'getMedia' : ActorMethod<[string], Media>,
  'getMindMap' : ActorMethod<[string], MindMap>,
  'getMindMapsBySession' : ActorMethod<[string], Array<MindMap>>,
  'getNote' : ActorMethod<[string], Note>,
  'getNotesBySession' : ActorMethod<[string], Array<Note>>,
  'getPodcast' : ActorMethod<[string], Podcast>,
  'getPodcastsBySession' : ActorMethod<[string], Array<Podcast>>,
  'getQuiz' : ActorMethod<[string], Quiz>,
  'getQuizzesBySession' : ActorMethod<[string], Array<Quiz>>,
  'getSession' : ActorMethod<[string], StudySession>,
  'processWithAI' : ActorMethod<[string, string, string], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateSessionStatus' : ActorMethod<[string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];