/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Media = IDL.Vec(IDL.Nat8);
export const Flashcard = IDL.Record({
  'front' : IDL.Text,
  'cardType' : IDL.Text,
  'back' : IDL.Text,
  'difficulty' : IDL.Text,
});
export const FlashcardTopic = IDL.Record({
  'id' : IDL.Text,
  'cards' : IDL.Vec(Flashcard),
  'sessionId' : IDL.Text,
  'topicName' : IDL.Text,
});
export const MindMap = IDL.Record({
  'id' : IDL.Text,
  'mapData' : IDL.Text,
  'sessionId' : IDL.Text,
});
export const Note = IDL.Record({
  'id' : IDL.Text,
  'content' : IDL.Text,
  'headings' : IDL.Vec(IDL.Text),
  'type' : IDL.Text,
  'sessionId' : IDL.Text,
});
export const Podcast = IDL.Record({
  'id' : IDL.Text,
  'script' : IDL.Text,
  'mode' : IDL.Text,
  'sessionId' : IDL.Text,
});
export const QuizQuestion = IDL.Record({
  'question' : IDL.Text,
  'explanation' : IDL.Text,
  'type' : IDL.Text,
  'answer' : IDL.Text,
  'options' : IDL.Vec(IDL.Text),
});
export const Quiz = IDL.Record({
  'id' : IDL.Text,
  'questions' : IDL.Vec(QuizQuestion),
  'sessionId' : IDL.Text,
});
export const StudySession = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'title' : IDL.Text,
  'subject' : IDL.Text,
  'createdAt' : IDL.Int,
  'sourceUrl' : IDL.Text,
  'sourceType' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addMedia' : IDL.Func([IDL.Text, Media], [], []),
  'createFlashcardTopic' : IDL.Func([FlashcardTopic], [], []),
  'createMindMap' : IDL.Func([MindMap], [], []),
  'createNote' : IDL.Func([Note], [], []),
  'createPodcast' : IDL.Func([Podcast], [], []),
  'createQuiz' : IDL.Func([Quiz], [], []),
  'createSession' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [StudySession],
      [],
    ),
  'deleteMedia' : IDL.Func([IDL.Text], [], []),
  'deleteSession' : IDL.Func([IDL.Text], [], []),
  'generateSampleContent' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'getAllSessions' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [IDL.Vec(StudySession)],
      ['query'],
    ),
  'getFlashcardTopic' : IDL.Func([IDL.Text], [FlashcardTopic], ['query']),
  'getFlashcardTopicsBySession' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(FlashcardTopic)],
      ['query'],
    ),
  'getMedia' : IDL.Func([IDL.Text], [Media], ['query']),
  'getMindMap' : IDL.Func([IDL.Text], [MindMap], ['query']),
  'getMindMapsBySession' : IDL.Func([IDL.Text], [IDL.Vec(MindMap)], ['query']),
  'getNote' : IDL.Func([IDL.Text], [Note], ['query']),
  'getNotesBySession' : IDL.Func([IDL.Text], [IDL.Vec(Note)], ['query']),
  'getPodcast' : IDL.Func([IDL.Text], [Podcast], ['query']),
  'getPodcastsBySession' : IDL.Func([IDL.Text], [IDL.Vec(Podcast)], ['query']),
  'getQuiz' : IDL.Func([IDL.Text], [Quiz], ['query']),
  'getQuizzesBySession' : IDL.Func([IDL.Text], [IDL.Vec(Quiz)], ['query']),
  'getSession' : IDL.Func([IDL.Text], [StudySession], ['query']),
  'processWithAI' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateSessionStatus' : IDL.Func([IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Media = IDL.Vec(IDL.Nat8);
  const Flashcard = IDL.Record({
    'front' : IDL.Text,
    'cardType' : IDL.Text,
    'back' : IDL.Text,
    'difficulty' : IDL.Text,
  });
  const FlashcardTopic = IDL.Record({
    'id' : IDL.Text,
    'cards' : IDL.Vec(Flashcard),
    'sessionId' : IDL.Text,
    'topicName' : IDL.Text,
  });
  const MindMap = IDL.Record({
    'id' : IDL.Text,
    'mapData' : IDL.Text,
    'sessionId' : IDL.Text,
  });
  const Note = IDL.Record({
    'id' : IDL.Text,
    'content' : IDL.Text,
    'headings' : IDL.Vec(IDL.Text),
    'type' : IDL.Text,
    'sessionId' : IDL.Text,
  });
  const Podcast = IDL.Record({
    'id' : IDL.Text,
    'script' : IDL.Text,
    'mode' : IDL.Text,
    'sessionId' : IDL.Text,
  });
  const QuizQuestion = IDL.Record({
    'question' : IDL.Text,
    'explanation' : IDL.Text,
    'type' : IDL.Text,
    'answer' : IDL.Text,
    'options' : IDL.Vec(IDL.Text),
  });
  const Quiz = IDL.Record({
    'id' : IDL.Text,
    'questions' : IDL.Vec(QuizQuestion),
    'sessionId' : IDL.Text,
  });
  const StudySession = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'title' : IDL.Text,
    'subject' : IDL.Text,
    'createdAt' : IDL.Int,
    'sourceUrl' : IDL.Text,
    'sourceType' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addMedia' : IDL.Func([IDL.Text, Media], [], []),
    'createFlashcardTopic' : IDL.Func([FlashcardTopic], [], []),
    'createMindMap' : IDL.Func([MindMap], [], []),
    'createNote' : IDL.Func([Note], [], []),
    'createPodcast' : IDL.Func([Podcast], [], []),
    'createQuiz' : IDL.Func([Quiz], [], []),
    'createSession' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [StudySession],
        [],
      ),
    'deleteMedia' : IDL.Func([IDL.Text], [], []),
    'deleteSession' : IDL.Func([IDL.Text], [], []),
    'generateSampleContent' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'getAllSessions' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [IDL.Vec(StudySession)],
        ['query'],
      ),
    'getFlashcardTopic' : IDL.Func([IDL.Text], [FlashcardTopic], ['query']),
    'getFlashcardTopicsBySession' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(FlashcardTopic)],
        ['query'],
      ),
    'getMedia' : IDL.Func([IDL.Text], [Media], ['query']),
    'getMindMap' : IDL.Func([IDL.Text], [MindMap], ['query']),
    'getMindMapsBySession' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(MindMap)],
        ['query'],
      ),
    'getNote' : IDL.Func([IDL.Text], [Note], ['query']),
    'getNotesBySession' : IDL.Func([IDL.Text], [IDL.Vec(Note)], ['query']),
    'getPodcast' : IDL.Func([IDL.Text], [Podcast], ['query']),
    'getPodcastsBySession' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Podcast)],
        ['query'],
      ),
    'getQuiz' : IDL.Func([IDL.Text], [Quiz], ['query']),
    'getQuizzesBySession' : IDL.Func([IDL.Text], [IDL.Vec(Quiz)], ['query']),
    'getSession' : IDL.Func([IDL.Text], [StudySession], ['query']),
    'processWithAI' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateSessionStatus' : IDL.Func([IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };